<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{bd6446df-a555-4a9a-9801-8a139cc9f785}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	rRoundedValue : REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[rRoundedValue := F_ROUND_REAL(10.655555, 3);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>