<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{d3c7fc20-9915-42b0-84f1-c5b81a710447}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb_TimeStamp : FB_UpdateTimeStamp ();
	
	bTestLamp	: BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Open PLC HMI view here C:\TwinCAT\3.1\Components\Plc\Tc3PlcHmi
// Open PLC HMI web view with this link   http://127.0.0.1/Tc3PlcHmiWeb/Port_851/Visu/webvisu.htm


fb_TimeStamp();
OP_BTN();

IF bTestLamp THEN
	
END_IF
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="11" Count="1" />
      <LineId Id="8" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="10" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="28" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="29" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>