<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="KUKA_IO" Id="{8ae2eb55-87e1-4ea9-a7b9-09ebadc6d917}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM KUKA_IO
VAR_INPUT
	LogText : STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[KR1();
KR2();
KR3();
KR4();
KR5();

]]></ST>
    </Implementation>
    <LineIds Name="KUKA_IO">
      <LineId Id="5" Count="4" />
      <LineId Id="14" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>